### ISSUE TITLE
Add default user to docker group

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/layer-docker#10]
Currently this only enables docker for the root user. Which is fine in context of Juju, but the system user when you juju ssh should have access to execute docker commands.

On ubuntu this is the ubuntu user, i need clarification on the centos default user.

**Comment by cloudguru-bb** [comment]
Chuck & friends .. what is the best way of adding name / value pairs for flags for insecure private registries .. including user, email, pwd that is required to pull images.

Currently my model has this is a .py file under /reactive dir.

**Comment by chuckbutler** [comment]
Greetings @cloudguru-bb 

We were taking a look at this, and have yet to decide if it belongs in relation data or via charm config. There is a module to pass this data to the underlying DockerOPTS file in this module: https://github.com/juju-solutions/charms.docker/blob/master/charms/docker/dockeropts.py

You can import it and consume as follows:

```python
from charms.docker.dockeropts import DockerOpts
from charmhelpers.core.templating import render

opts = DockerOpts()
opts.add('insecure-registry', '127.0.0.1:3000')
render('docker.defaults', '/etc/default/docker', {'opts': opts.to_s()})
```

If you have any further questions about how to integrate, i'm a fan of looking at the code you used to implement it so we can extract and bring it into the charms.docker library space.  Hope this helps!

**Comment by chuckbutler** [comment]
This was resolved a while back, and due to the nature of series-in-metadata, this becomes a bit of a non-starter considering layer-docker has support for centos hosts in install, it has a lot of ubuntu specific bits that I feel negate the cross-platform nature of the above comments.

Closing as resolved
