### ISSUE TITLE
Switch to common copyright license

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/layer-docker#102]
Is it possible to switch to a common copyright license? The current license is a strange snowflake license. It doesn't even have a name, so I can't look up if its gpl compatible etc..

I'm very hesitant to touch the code without a bunch of lawyers by my side...

**Comment by Cynerva** [comment]
@galgalesh The [copyright](https://github.com/juju-solutions/layer-docker/blob/master/copyright) file in this repo looks like the [4-clause BSD license](https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_.28original_.22BSD_License.22.29) to me, for what it's worth

**Comment by chuckbutler** [comment]
@Cynerva it is the bsd-4clause license. I'm not married to it however and I'm fine with moving it to something more consistent with our other layers/charms like the ASL 2.0

**Comment by galgalesh** [comment]
Thanks for clearing that up!

I've looked up the license and the main issue with this license is that it's not gpl compatible. ASL 2.0 is perfect! That would mean we can use it in our agplv3 licenced code.

**Comment by galgalesh** [comment]
Awesome, thanks Chuck!

Op woensdag 11 januari 2017 heeft Charles Butler <notifications@github.com>
het volgende geschreven:
> Closed #102 via #103.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/gHbP7bUZvqp3RFYz33amoOVumwFsnr4_YzoBOLc0se7aRpmArNSaWPcI_lYLYQ8T_TeatBYnqsEMAP2bNpkL5Uc7xZ5MjQf2D8DR_y0gm_dh9ncFdlmcKwFQC5jsnOmoB8XnTbu2x0pCOjZmOtgAm6DxvPKyIw=s0-d-e1-ft#https://github.com/notifications/beacon/ABbH9YsnyMwGJg4JmGO67hV-pfbZsdnDks5rRQ_egaJpZM4LcBvz.gif>

**Comment by chuckbutler** [comment]
No problem Merlijin 👍
