### ISSUE TITLE
Unable to install kubernetes: apt-key not working behind corporate http proxy

### ISSUE THREAD

**Issue by ethbo** [juju-solutions/layer-docker#126]
Unfortunately, apt-key is not able to import keys by id if executed behind a corporate http proxy. As far as I understand, apt-key utilizes gnupg which in the current version ignores all proxy-related environment variables and former proxy options. I'd suggest to check if proxy-related environment variables are defined and in that case use curl to fetch the file first instead of calling apt-key directly.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809366.
