### ISSUE TITLE
enable cAdvisor for the docker charm

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-docker#15]
There are some features that are not enabled on the charm resulting from the layer-docker.  One example of this is cAdvisor.  According to the docker logs from kubelet:

kubelet_1 | E1028 21:48:44.889820   20022 kubelet.go:2016] Error getting machine info: cAdvisor is unsupported in this build

The layer-docker does the aufs install if that is not available.  We should also enable cAdvisor if possible.

Here is a [link to the Kubernetes prerequsites](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md#prerequisites) that detail some other required things.

**Comment by mbruzek** [comment]
more log messages:
kubelet_1 | E1028 21:48:44.126421   20022 kubelet.go:2016] Error getting machine info: cAdvisor is unsupported in this build
kubelet_1 | E1028 21:48:44.126492   20022 kubelet.go:2035] Error getting version info: cAdvisor is unsupported in this build
kubelet_1 | I1028 21:48:44.137929   20022 kubelet.go:702] Running in container "/kubelet"
kubelet_1 | E1028 21:48:44.161178   20022 kubelet.go:712] Failed to start CAdvisor, system may not be properly monitored: cAdvisor is unsupported in this build
kubelet_1 | E1028 21:48:44.161230   20022 kubelet.go:722] Failed to start OOM watching: cAdvisor is unsupported in this build

**Comment by chuckbutler** [comment]
Even after updating the daemon to boot with those grub flags, its still spewing errors about CAdvisor not being available for the build. I've re-opened this against the layer-k8's for tracking until there is further action to take here.
