### ISSUE TITLE
reminder to sync the install_docker.sh script from time to time

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-docker#22]
The install_docker.sh file does not track upstream changes, we should remember to re-sync with docker's version at regular intervals to pick up any changes/improvements.

**Comment by chuckbutler** [comment]
+1 to this, i have a script that diffs the upstream script and what we have in the charm. I need to get this somewhere public, and have it register bugs on the tracker if it deviates more than what we expect. Sounds like a friday hack session to me.

**Comment by chuckbutler** [comment]
I think we're going to remix this approach and fully deprecate the packed install.sh script and instead carry forward 2 options which mirrors the behavior of the docker charm:

Now that the docker.io package has some maintainers:

- Move to installing docker.io by default (prepare yourself, this comes with the fan and some other preconfigured bits we need to be prepared for
- Cut out the non-ubuntu specific install bits, and leave that behind as an upstream install method
- Add the config option to switch between the two (this gets messy when there are workloads deployed)

I don't think keeping this script "in sync" will be enough anymore as we move further into the territory of stuff we are pressing/using/testing vs just relying on the upstream install.sh script to break.

**Comment by chuckbutler** [comment]
Invalid as of #56
