### ISSUE TITLE
private registries deprecated?

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-docker#23]
While debugging a charm that uses this layer I noticed an error message that we should investigate or plan to fix sometime.

gcr.io/google_containers/etcd: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.

What will 'future' docker do with private registries?  Is there anything we can do at the layer level to future proof ourselves?

**Comment by chuckbutler** [comment]
This is an indicator that the docker registry being pulled from is a v1 registry. The registry actually is renamed to `distribution` and has a v2 api. Once gcr.io upgrades to the v2 distribution, this error message will go away.

That warning is a deprecation notice from the docker project that they are going to fully deprecate v1 registries. However I do imagine that they will provide an insecure flag that will allow you to pull from a legacy archive, but that is not certain. I haven't heard one way or the other how it will be finalized, but id o know that by default, you will be nagged to upgrade your registry.
