### ISSUE TITLE
Track / Remove xenial patch when 16.04 lands

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/layer-docker#25]
Docker 1.10 will not deploy cleanly from their PPA on Xenial as it's not officially released.

To not halt progress a patch was applied to `scripts/install_docker.sh` that should go away when xenial support is officially landed in the docker ppa.

**Comment by mbruzek** [comment]
We should also sync with the new docker shell script.

**Comment by chuckbutler** [comment]
Series in metadata negates the need to carry those bits actually....

This should be split up into different bases for the different series it will support. No reason to track centos in an ubuntu charm right?

**Comment by chuckbutler** [comment]
This is prelim work for #21
