### ISSUE TITLE
docker-compose doesn't install -> install fail 

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/layer-docker#31]
At least on GCE, using the docker layer fails

* First there is a "skip-install" error from the apt-get install docker-compose command that fails, so we need to add this parameter to the install command. 
* Then 

```
unit-deepdetect-0[13248]: 2016-03-31 14:06:28 INFO unit.deepdetect/0.install logger.go:40     check_call(['apt-get', 'install', '-y', 'docker-compose'])
unit-deepdetect-0[13248]: 2016-03-31 14:06:28 INFO unit.deepdetect/0.install logger.go:40   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
unit-deepdetect-0[13248]: 2016-03-31 14:06:28 INFO unit.deepdetect/0.install logger.go:40     raise CalledProcessError(retcode, cmd)
unit-deepdetect-0[13248]: 2016-03-31 14:06:28 INFO unit.deepdetect/0.install logger.go:40 subprocess.CalledProcessError: Command '['apt-get', 'install', '-y', 'docker-compose']' returned non-zero exit status 100
unit-deepdetect-0[13248]: 2016-03-31 14:06:28 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
```

Happy to help resolving.

**Comment by chuckbutler** [comment]
Potential fix in #30 - reviews welcome on the approach to the fix

**Comment by chuckbutler** [comment]
@SaMnCo - #30 just got merged, can you give this another go and report back if you have any further issues?

I also recommend you wipe your 'deps' directory that charm-build uses to ensure you don't grab a cached  copy when building.  This is important as the docker-compose bits have been moved into the wheelhouse and are now isolated in the charm runtime.

**Comment by chuckbutler** [comment]
if this continues to be an issue, please re-open the issue and update us with the status of the nature of the failure. Thanks for reporting this one @SaMnCo
