### ISSUE TITLE
Docker installation breaks when using custom docker opts

### ISSUE THREAD

**Issue by simonklb** [juju-solutions/layer-docker#51]
When adding an insecure registry using the dockeropts module described in https://github.com/juju-solutions/layer-docker/issues/10#issuecomment-168690507 the docker-engine installation breaks due to the following halting message:

```
Setting up docker-engine (1.11.1-0~xenial) ...

Configuration file '/etc/default/docker'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** docker (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package docker-engine (--configure):
 end of file on stdin at conffile prompt
Errors were encountered while processing:
 docker-engine
E: Sub-process /usr/bin/dpkg returned an error code (1)
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-testcharm-12/charm/hooks/install", line 19, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 421, in dispatch
    _invoke(other_handlers)
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 404, in _invoke
    handler.invoke()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 280, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-testcharm-12/charm/reactive/docker.py", line 51, in install
    check_call([install_script_path])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-testcharm-12/charm/scripts/install_docker.sh']' returned non-zero exit status 100
juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
```

Juju version: 2.0-beta6-xenial-amd64
Charm series: xenial
Provider: LXD

Relevant issue: https://github.com/docker/docker/issues/12124

**Comment by mbruzek** [comment]
Hello @simonklb thanks for creating the issue and linking the relevant docker issue. We hope they can fix that soon.

The LXD provider needs a custom profile before it will run docker correctly. The required docker profile is not provided to the LXD environment by Juju at this time. Check this bug to track that progress: https://bugs.launchpad.net/juju-core/+bug/1552815

**Comment by simonklb** [comment]
> Hello @simonklb thanks for creating the issue and linking the relevant docker issue. We hope they can fix that soon.

Hi @mbruzek !
Unfortunately it seems, when reading the docker issue, that the docker devs does not think this issue is theirs to fix as it would be bad if they were making that decision without knowing the user's intent.

I'm actually not looking for a fix for the problem brought up in the docker issue, but rather a fix to be able to use custom docker daemon options. If it's by modifying the docker installation script and automatically "keep your currently-installed version" or something else doesn't really matter to me.

> The LXD provider needs a custom profile before it will run docker correctly.

Yes, I've subscribed to the bug-thread before and is hoping for a fix for that soon as well! Though, I don't think this is the cause of the issue at hand.

**Comment by marcoceppi** [comment]
It seems like we'd just want force conf either way (package, or local) and make sure we run `charms.docker.dockeropts.to_str` to re-render the configuration

**Comment by chuckbutler** [comment]
Decent thread to come into this morning :) 

Lets start at the top:  @simonklb thanks for filing this bug. I haven't run into this personally so its great to see the community pitching in so quickly to find a resolution.

This is going to bleed into another topic that surfaced from the linked docker issue: 

> We're in the process of phasing out the get.docker.com install script in favor of manually adding the 
> repos; #16662, and I would recommend using those steps in your automated script (customizing it to your needs)

We're going to deprecate the shipping script this cycle and move to a more focused installation path that offers you a choice between archive, or upstream ppa. 

Regarding the configuration file changed and the apt script needing updating - marco's hotfix will carry us until we get to the 1.0.0 release of layer-docker which will fully deprecate the modified/embedded upstream install script.

Thanks again for everyone taking a look and working quickly to release a fix.
