### ISSUE TITLE
The python refactor needs to include AUFS correctly

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-docker#59]
The python refactor of the docker install script does not do AUFS correctly. 

We should fix this.

**Comment by chuckbutler** [comment]
I wonder if we shouldn't instead support overlay2 at this point...

**Comment by mbruzek** [comment]
keep up the good fight @chuckbutler

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809369.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809370.
