### ISSUE TITLE
Need to resolve README concerns

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-docker#8]
The README.md of a layer needs to be descriptive for other people to know how to consume this layer, but the matching files (other README.md files) will overwrite the README.md in the composed charm.

We should come up with a best practice for this.

**Comment by chuckbutler** [comment]
This is more of a concern w/ how layer building occurs, and should be directed @ the juju list. I'm OK with the docker layer README getting overwritten as its not intended to be a top level charm. its a framework scaffolded base to provide docker to other layers.
