### ISSUE TITLE
signal_workload_start() does not attempt to start docker

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-docker#83]
While debugging another problem we noticed that the `docker.available` state is used to know when the docker daemon is running. 

The `signal_workload_start()` method only checks if docker is running, but never attempts to start it. 

We should attempt to start docker if we know it is not responding.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809374.
